#!/bin/bash

# FIX B2: Script to generate secure JWT secret
# Run this once to generate a secure random JWT secret

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 JWT SECRET GENERATOR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Generating secure random JWT secret..."
echo ""

# Generate a secure random 64-byte base64 encoded string
JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')

echo "✅ Generated JWT Secret:"
echo ""
echo "$JWT_SECRET"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 SETUP INSTRUCTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 1: Set as environment variable (recommended for development)"
echo ""
echo "  export JWT_SECRET=\"$JWT_SECRET\""
echo ""
echo "Then run your app:"
echo "  ./mvnw spring-boot:run"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 2: Add to .env file (for production)"
echo ""
echo "Create a file named .env in the backend directory:"
echo ""
echo "  JWT_SECRET=$JWT_SECRET"
echo ""
echo "⚠️  IMPORTANT: Add .env to .gitignore!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 3: Quick setup (run this command now)"
echo ""
echo "  export JWT_SECRET=\"$JWT_SECRET\" && ./mvnw spring-boot:run"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  SECURITY WARNING:"
echo "   - NEVER commit this secret to git"
echo "   - Use different secrets for dev/staging/production"
echo "   - Rotate secrets regularly"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
